/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as FontSlugRouteImport } from './routes/font.$slug'
import { Route as FontsIndexRouteImport } from './routes/fonts.index'
import { Route as FontsHubRouteImport } from './routes/fonts.$hub'
import { Route as ZhTwIndexRouteImport } from './routes/zh-tw.index'
import { Route as ZhIndexRouteImport } from './routes/zh.index'
import { Route as ZhTwFontSlugRouteImport } from './routes/zh-tw.font.$slug'
import { Route as ZhTwFontsIndexRouteImport } from './routes/zh-tw.fonts.index'
import { Route as ZhTwFontsHubRouteImport } from './routes/zh-tw.fonts.$hub'
import { Route as ZhFontSlugRouteImport } from './routes/zh.font.$slug'
import { Route as ZhFontsIndexRouteImport } from './routes/zh.fonts.index'
import { Route as ZhFontsHubRouteImport } from './routes/zh.fonts.$hub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FontSlugRoute = FontSlugRouteImport.update({
  id: '/font/$slug',
  path: '/font/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsIndexRoute = FontsIndexRouteImport.update({
  id: '/fonts/',
  path: '/fonts/',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsHubRoute = FontsHubRouteImport.update({
  id: '/fonts/$hub',
  path: '/fonts/$hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhTwIndexRoute = ZhTwIndexRouteImport.update({
  id: '/zh-tw/',
  path: '/zh-tw/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhTwFontSlugRoute = ZhTwFontSlugRouteImport.update({
  id: '/zh-tw/font/$slug',
  path: '/zh-tw/font/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhTwFontsIndexRoute = ZhTwFontsIndexRouteImport.update({
  id: '/zh-tw/fonts/',
  path: '/zh-tw/fonts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhTwFontsHubRoute = ZhTwFontsHubRouteImport.update({
  id: '/zh-tw/fonts/$hub',
  path: '/zh-tw/fonts/$hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFontSlugRoute = ZhFontSlugRouteImport.update({
  id: '/zh/font/$slug',
  path: '/zh/font/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFontsIndexRoute = ZhFontsIndexRouteImport.update({
  id: '/zh/fonts/',
  path: '/zh/fonts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFontsHubRoute = ZhFontsHubRouteImport.update({
  id: '/zh/fonts/$hub',
  path: '/zh/fonts/$hub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/font/$slug': typeof FontSlugRoute
  '/fonts/$hub': typeof FontsHubRoute
  '/fonts/': typeof FontsIndexRoute
  '/zh-tw/': typeof ZhTwIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/zh-tw/font/$slug': typeof ZhTwFontSlugRoute
  '/zh-tw/fonts/$hub': typeof ZhTwFontsHubRoute
  '/zh/font/$slug': typeof ZhFontSlugRoute
  '/zh/fonts/$hub': typeof ZhFontsHubRoute
  '/zh-tw/fonts/': typeof ZhTwFontsIndexRoute
  '/zh/fonts/': typeof ZhFontsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/font/$slug': typeof FontSlugRoute
  '/fonts/$hub': typeof FontsHubRoute
  '/fonts': typeof FontsIndexRoute
  '/zh-tw': typeof ZhTwIndexRoute
  '/zh': typeof ZhIndexRoute
  '/zh-tw/font/$slug': typeof ZhTwFontSlugRoute
  '/zh-tw/fonts/$hub': typeof ZhTwFontsHubRoute
  '/zh/font/$slug': typeof ZhFontSlugRoute
  '/zh/fonts/$hub': typeof ZhFontsHubRoute
  '/zh-tw/fonts': typeof ZhTwFontsIndexRoute
  '/zh/fonts': typeof ZhFontsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/font/$slug': typeof FontSlugRoute
  '/fonts/$hub': typeof FontsHubRoute
  '/fonts/': typeof FontsIndexRoute
  '/zh-tw/': typeof ZhTwIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/zh-tw/font/$slug': typeof ZhTwFontSlugRoute
  '/zh-tw/fonts/$hub': typeof ZhTwFontsHubRoute
  '/zh/font/$slug': typeof ZhFontSlugRoute
  '/zh/fonts/$hub': typeof ZhFontsHubRoute
  '/zh-tw/fonts/': typeof ZhTwFontsIndexRoute
  '/zh/fonts/': typeof ZhFontsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/api/health'
    | '/font/$slug'
    | '/fonts/$hub'
    | '/fonts/'
    | '/zh-tw/'
    | '/zh/'
    | '/zh-tw/font/$slug'
    | '/zh-tw/fonts/$hub'
    | '/zh/font/$slug'
    | '/zh/fonts/$hub'
    | '/zh-tw/fonts/'
    | '/zh/fonts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/api/health'
    | '/font/$slug'
    | '/fonts/$hub'
    | '/fonts'
    | '/zh-tw'
    | '/zh'
    | '/zh-tw/font/$slug'
    | '/zh-tw/fonts/$hub'
    | '/zh/font/$slug'
    | '/zh/fonts/$hub'
    | '/zh-tw/fonts'
    | '/zh/fonts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/api/health'
    | '/font/$slug'
    | '/fonts/$hub'
    | '/fonts/'
    | '/zh-tw/'
    | '/zh/'
    | '/zh-tw/font/$slug'
    | '/zh-tw/fonts/$hub'
    | '/zh/font/$slug'
    | '/zh/fonts/$hub'
    | '/zh-tw/fonts/'
    | '/zh/fonts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  FontSlugRoute: typeof FontSlugRoute
  FontsHubRoute: typeof FontsHubRoute
  FontsIndexRoute: typeof FontsIndexRoute
  ZhTwIndexRoute: typeof ZhTwIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  ZhTwFontSlugRoute: typeof ZhTwFontSlugRoute
  ZhTwFontsHubRoute: typeof ZhTwFontsHubRoute
  ZhFontSlugRoute: typeof ZhFontSlugRoute
  ZhFontsHubRoute: typeof ZhFontsHubRoute
  ZhTwFontsIndexRoute: typeof ZhTwFontsIndexRoute
  ZhFontsIndexRoute: typeof ZhFontsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font/$slug': {
      id: '/font/$slug'
      path: '/font/$slug'
      fullPath: '/font/$slug'
      preLoaderRoute: typeof FontSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts/': {
      id: '/fonts/'
      path: '/fonts'
      fullPath: '/fonts/'
      preLoaderRoute: typeof FontsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts/$hub': {
      id: '/fonts/$hub'
      path: '/fonts/$hub'
      fullPath: '/fonts/$hub'
      preLoaderRoute: typeof FontsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-tw/': {
      id: '/zh-tw/'
      path: '/zh-tw'
      fullPath: '/zh-tw/'
      preLoaderRoute: typeof ZhTwIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-tw/font/$slug': {
      id: '/zh-tw/font/$slug'
      path: '/zh-tw/font/$slug'
      fullPath: '/zh-tw/font/$slug'
      preLoaderRoute: typeof ZhTwFontSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-tw/fonts/': {
      id: '/zh-tw/fonts/'
      path: '/zh-tw/fonts'
      fullPath: '/zh-tw/fonts/'
      preLoaderRoute: typeof ZhTwFontsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-tw/fonts/$hub': {
      id: '/zh-tw/fonts/$hub'
      path: '/zh-tw/fonts/$hub'
      fullPath: '/zh-tw/fonts/$hub'
      preLoaderRoute: typeof ZhTwFontsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/font/$slug': {
      id: '/zh/font/$slug'
      path: '/zh/font/$slug'
      fullPath: '/zh/font/$slug'
      preLoaderRoute: typeof ZhFontSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/fonts/': {
      id: '/zh/fonts/'
      path: '/zh/fonts'
      fullPath: '/zh/fonts/'
      preLoaderRoute: typeof ZhFontsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/fonts/$hub': {
      id: '/zh/fonts/$hub'
      path: '/zh/fonts/$hub'
      fullPath: '/zh/fonts/$hub'
      preLoaderRoute: typeof ZhFontsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiHealthRoute: ApiHealthRoute,
  FontSlugRoute: FontSlugRoute,
  FontsHubRoute: FontsHubRoute,
  FontsIndexRoute: FontsIndexRoute,
  ZhTwIndexRoute: ZhTwIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  ZhTwFontSlugRoute: ZhTwFontSlugRoute,
  ZhTwFontsHubRoute: ZhTwFontsHubRoute,
  ZhFontSlugRoute: ZhFontSlugRoute,
  ZhFontsHubRoute: ZhFontsHubRoute,
  ZhTwFontsIndexRoute: ZhTwFontsIndexRoute,
  ZhFontsIndexRoute: ZhFontsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
